ALTER TABLE leave_applications
ADD COLUMN IF NOT EXISTS hod_approved_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS admin_deadline TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS auto_approved_by_system BOOLEAN DEFAULT FALSE;